server:
  address: ":8080"

routes:
  - name: users-read
    methods: [GET]
    path_prefix: /users
    upstream_pool: users-service

  - name: users-write
    methods: [POST, PUT, DELETE]
    path_prefix: /users
    upstream_pool: users-service

upstream_pools:
  - name: users-service
    targets:
      - http://localhost:8081
